# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 81f33bb
_src_path: gh:blakeNaccarato/copier-python-init
actions_runner: ubuntu-latest
advanced: false
docs_engine: MYST
github_repo_name: thread
include_funding: true
override: false
override_codecov: false
override_coveragerc: false
override_env: false
override_flake8: true
override_gitattributes: false
override_gitignore: false
override_isort: false
override_markdownlint: false
override_precommit: false
override_pyrightconfig: false
override_pytest: false
override_sourcery: false
override_update: false
override_vscode_extensions: false
override_vscode_launch: false
override_vscode_settings: false
override_vscode_tasks: true
project_email: blake.naccarato+thread@gmail.com
project_name: thread
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
use_dvc: false
year_of_project_creation: 2022
