# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: b9d35cb
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
active: false
github_repo_name: lookback
project_description: Utilities for analyzing Trello boards for time tracking, estimation,
    report writing, and more.
project_email: blake.naccarato@gmail.com
project_name: lookback
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
project_version: 0.0.0
python_version: '3.11'
year_of_project_creation: 2022
