# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ef06f56
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
advanced: false
docs_engine: MyST
github_repo_name: lookback
include_funding: true
project_email: blake.naccarato+lookback@gmail.com
project_name: lookback
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
year_of_project_creation: 2022
