[build-system]
requires = ["flit_core >=3.3,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "thread"
requires-python = ">=3.11"
dependencies = ["datamodel-code-generator~=0.16.0", "pyperclip~=1.8.2", "typer~=0.7.0"]
readme = "README.md"
dynamic = ["version", "description"]
[[project.authors]]
name = "Blake Naccarato"
email = "blake.naccarato+thread@gmail.com"

[project.urls]
Home = "https://github.com/blakeNaccarato/thread"

[project.scripts]
thread = "thread.cli:app"

[project.optional-dependencies]
